objects = buffer.o devices.o fcntl.o filesystems.o inode.o ioctl.o namei.o \
	  open.o read_write.o stat.o super.o ramfs/ramfs.o binfs/binfs.o \
	  modfs/modfs.o ext2/super.o ext2/inode.o ext2/dir.o ext2/file.o
clean = $(objects)

all: $(objects)

include $(topdir)/rules.mk
