objects = devices.o filesystems.o inode.o ioctl.o namei.o open.o read_write.o \
	  stat.o super.o ramfs/ramfs.o binfs/binfs.o modfs/modfs.o
clean = $(objects)

all: $(objects)

include $(topdir)/rules.mk
